CC = gcc
TARGETS = parallel_sum

all: $(TARGETS)

# Сборка parallel_sum
parallel_sum: parallel_sum.c sum_lib.c utils.c
	$(CC) -o $@ parallel_sum.c sum_lib.c utils.c

# Тест для parallel_sum
test: parallel_sum
	@echo "Тест parallel_sum"
	./parallel_sum --threads_num 4 --array_size 1000 --seed 42

# Очистка
clean:
	rm -f parallel_sum

.PHONY: all clean test